### PR TITLE
fix: resolve ListTableModel race condition with exception handling

### LINKED ISSUE #379: EDT race condition in ListTableModel causing IndexOutOfBoundsException
`ListTableModel.getValueAt()` passes the row index directly to the `LinkedList` without bounds checking. Because Swing reads `getRowCount()` and `getValueAt()` in separate steps on the EDT, this seems to cause a race condition that results in a stale index being used against an already-empty list.

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
    at java.util.LinkedList.checkElementIndex(LinkedList.java:566)
    at java.util.LinkedList.get(LinkedList.java:487)
    at io.confluent.intellijplugin.common.editor.ListTableModel.getValueAt(ListTableModel.kt:29)
    at javax.swing.JTable.getValueAt(JTable.java:2769)
    at javax.swing.JTable.prepareRenderer(JTable.java:5800)
    at com.intellij.ui.table.JBTable.prepareRenderer(JBTable.java:733)
    at io.confluent.intellijplugin.core.table.MaterialTable.prepareRenderer(MaterialTable.kt:194)
    at javax.swing.JTable.getToolTipText(JTable.java:3445)
    at com.intellij.ide.IdeTooltipManager.isTooltipDefined(IdeTooltipManager.kt:428)
    at com.intellij.ide.IdeTooltipManager.showForComponent(IdeTooltipManager.kt:389)
    at com.intellij.ide.IdeTooltipManager.maybeShowFor(IdeTooltipManager.kt:376)
    at com.intellij.ide.IdeTooltipManager.eventDispatched$intellij_platform_ide_impl(IdeTooltipManager.kt:296)
    at com.intellij.ide.SwingTooltipManagerCustomizer.execute$lambda$2(IdeTooltipManager.kt:68)
    at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2204)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2096)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2095)
    at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2052)
    at java.awt.Component.dispatchEventImpl(Component.java:4955)
    at java.awt.Container.dispatchEventImpl(Container.java:2324)
    at java.awt.Component.dispatchEvent(Component.java:4877)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
    at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4728)
    at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4706)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4557)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
    at java.awt.Container.dispatchEventImpl(Container.java:2310)
    at java.awt.Window.dispatchEventImpl(Window.java:2823)
    at java.awt.Component.dispatchEvent(Component.java:4877)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
    at java.awt.EventQueue$4.run(EventQueue.java:728)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
```

### PR DESCRIPTION
**Pull request by bcscc**
## Summary of Changes

- `getValueAt()` now catches exceptions from concurrent list access, returning `null` for stale or invalid row indices instead of crashing
- Fixes a race condition where Swing's tooltip system uses a cached row index from a prior EDT event after the table data has been cleared
- Adds `ListTableModelTest` covering bounds checking, eviction, and concurrent read/write safety

> **Follow-up:** A more permanent fix should be addressed as part of the MessageViewer upgrade. Tracked in #390. cc @noeldevelops

### Optional: Click-testing instructions

1. Start consuming, open a topic with records flowing in, verify the table populates normally
2. Tooltip hover during consumption, hover over cells while messages are actively arriving, confirm no crash and tooltips display correctly
3. Stop and clear, stop the consumer, clear the table, then immediately move your mouse across where rows used to be. This is the exact scenario from the stack trace (tooltip on stale row index after clear)
4. Rapid clear while hovering, hover over a populated row, then trigger clear. The mouse position is now a stale index against an empty list
5. Max elements eviction, set a low maxElementsCount, let messages flow until eviction kicks in, hover over the top rows as they're being evicted
6. Producer output, repeat steps 2-4 on the producer results table (KafkaProducerEditor also uses ListTableModel)

### Optional: Any additional details or context that should be provided?

- Fixes #379

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

#### Tests

- [x] Added new
- [ ] Updated existing
- [ ] Deleted existing

### CODE REVIEW

**Review by flippingbits — DISMISSED** [review]

File: src/io/confluent/intellijplugin/common/editor/ListTableModel.kt [hunk 1]
```diff
@@ -26,12 +26,15 @@ class ListTableModel<T>(
 
     override fun getRowCount() = data.size
     override fun getColumnCount() = columnNames.size
-    override fun getValueAt(rowIndex: Int, columnIndex: Int) = columnMapper(data[rowIndex], columnIndex)
+    override fun getValueAt(rowIndex: Int, columnIndex: Int): Any? {
+        val row = data.getOrNull(rowIndex) ?: return null
+        return columnMapper(row, columnIndex)
+    }
```
[the remark this answers is not in the document]
Comment (flippingbits) [reply src/io/confluent/intellijplugin/common/editor/ListTableModel.kt]: I think that's a fair point. It seems the class is not covered with tests right now. Maybe bootstrap the tests and include one that's verifying the race condition fix?

[the remark this answers is not in the document]
Comment (bcscc) [reply src/io/confluent/intellijplugin/common/editor/ListTableModel.kt]: Added testing with a concurrent stress test but found that `getOrNull` also checks bounds then calls `get()` as two separate steps so it doesn't fix the bug 😅. Consulted with Noel and decided to use a broad catch for now since the underlying LinkedList can throw multiple exception types under concurrent modification. We'll address this properly when we do the MessageViewer upgrade (#390)

File: src/io/confluent/intellijplugin/common/editor/ListTableModel.kt [hunk 2]
```diff
@@ -26,12 +26,16 @@ class ListTableModel<T>(
 
     override fun getRowCount() = data.size
     override fun getColumnCount() = columnNames.size
-    override fun getValueAt(rowIndex: Int, columnIndex: Int) = columnMapper(data[rowIndex], columnIndex)
+    // Guard against stale indices from concurrent list modification.
+    // TODO: address with MessageViewer upgrade
+    override fun getValueAt(rowIndex: Int, columnIndex: Int): Any? =
+        try { columnMapper(data[rowIndex], columnIndex) } catch (_: Exception) { null }
```
Comment (flippingbits) [inline src/io/confluent/intellijplugin/common/editor/ListTableModel.kt]: I know it's a temporary fix but could we still log the exception so that we don't silently swallow and lose access to the error?

**Review by flippingbits — COMMENTED** [review]
Thanks for adding tests 🥇 I have one more minor comment on the handling of the exceptions.

File: src/io/confluent/intellijplugin/common/editor/ListTableModel.kt [hunk 3]
```diff
@@ -26,12 +27,21 @@ class ListTableModel<T>(
...
+            thisLogger().warn(e)
+            null
+        }
     override fun getColumnClass(columnIndex: Int): Class<*> {
         return columnClasses?.get(columnIndex) ?: super.getColumnClass(columnIndex)
     }
 
-    fun getValueAt(rowIndex: Int): T? = if (rowIndex in data.indices) data[rowIndex] else null
+    fun getValueAt(rowIndex: Int): T? =
+        try { data[rowIndex] } catch (_: Exception) { null }
```
Comment (flippingbits) [inline src/io/confluent/intellijplugin/common/editor/ListTableModel.kt]: Apologies for not calling it out. Could you also add a log statement here?

Comment (bcscc) [reply src/io/confluent/intellijplugin/common/editor/ListTableModel.kt]: Sorry missed that, fixed!

**Review by flippingbits — APPROVED** [review]
Thank you!
