### PR TITLE
Fix OAuth sign-in EDT violation error

### LINKED ISSUE #325: EDT Violation: TreeUI Accessed from Background Thread During OAuth Callback
## Summary
OAuth login callback triggers UI updates from a background thread instead of the EDT (Event Dispatch Thread), violating IntelliJ Platform's threading requirements and causing TreeUI should be accessed only from EDT errors.

## Steps to Reproduce
Based on [this branch](https://github.com/confluentinc/intellij/pull/323) (merged)
1. Open Kafka plugin tool window
2. Navigate to "Confluent Cloud" tab
3. Click "Sign in with OAuth"
4. Complete authentication in browser
5. Browser redirects to callback URL
6. Observe error in IDE logs/terminal

##  Expected Behavior
OAuth callback completes successfully
Resources tree view displays without errors
All UI updates execute on EDT

## Actual Behavior
Resources tree view loads successfully BUT logs show EDT violation warning:
`java.lang.Throwable: TreeUI should be accessed only from EDT`
Image

### PR DESCRIPTION
**Pull request by eguicf**
## Summary of Changes

Closes #325 
Fixes EDT violation during OAuth sign-in by ensuring UI callbacks execute on the Event Dispatch Thread.

## Changes
- Added `withContext(Dispatchers.EDT)` around UI callbacks in `CCloudAuthService.signIn()`
- Keeps password storage and telemetry on `Dispatchers.IO` for performance
- Switches to EDT only for final UI updates (tree view, notifications)

### Optional: Click-testing instructions

`./gradlew runIde `
no warnings/issues from terminal.

### Optional: Any additional details or context that should be provided?

-

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

#### Tests

- [ ] Added new
- [ ] Updated existing
- [ ] Deleted existing

### CODE REVIEW

File: src/io/confluent/intellijplugin/ccloud/client/CCloudRestClient.kt [hunk 1]
```diff
@@ -11,7 +11,6 @@ import kotlinx.coroutines.withContext
 import kotlinx.serialization.SerialName
 import kotlinx.serialization.Serializable
 import java.net.HttpURLConnection
-import kotlin.math.max
```
Comment (noeldevelops) [inline src/io/confluent/intellijplugin/ccloud/client/CCloudRestClient.kt:14]: unrelated?

**Review by noeldevelops — DISMISSED** [review]
tried this out locally and don't see any issues 👍

File: src/io/confluent/intellijplugin/ccloud/client/CCloudRestClient.kt (hunk 1 above)
Comment (eguicf) [reply src/io/confluent/intellijplugin/ccloud/client/CCloudRestClient.kt:14]: Yes, this was only a cleanup, apologies for not commenting on it.

**Comment by eguicf** [comment]
Thanks for reviewing @noeldevelops! 
I replaced `runBlocking` with `CoroutineScope.launch` for better practice, and to avoid blocking the IO thread during UI updates.

File: src/io/confluent/intellijplugin/ccloud/fetcher/ControlPlaneFetcher.kt [hunk 2]
```diff
@@ -1,6 +1,8 @@
 package io.confluent.intellijplugin.ccloud.fetcher
 
-import io.confluent.intellijplugin.ccloud.model.*
+import io.confluent.intellijplugin.ccloud.model.Cluster
```
Comment (eguicf) [inline src/io/confluent/intellijplugin/ccloud/fetcher/ControlPlaneFetcher.kt:3]: Unrelated, import improvements by clicking "reformat code" provided by IntelliJ IDE.

**Review by noeldevelops — APPROVED** [review]
this is working well for me locally 🍰 

Does it seem like it sped up the loading time in general also? Just wondering if that was part of the problem with #324 as well

**Comment by eguicf** [comment]
> this is working well for me locally 🍰
> 
> Does it seem like it sped up the loading time in general also? Just wondering if that was part of the problem with #324 as well

sometimes I feel like it sped up a little as well, but couldn't find any explanation. I will continue looking into https://github.com/confluentinc/intellij/issues/324.
