### PR TITLE
bubble up CCloud auth result errors instead of relying on wider net 

### LINKED ISSUE #394: Catch OAuth sign-in failed error instead of bubbling to ide error reporter
Image

### PR DESCRIPTION
**Pull request by Cerchie**
## Summary of Changes

Fixes #394 by adding try/catch blocks around result logic. 

### Click-testing instructions

Run tests locally, ensure they pass. Check that signing in after `gradlew runIde` works as expected. 

No idea why it's both 33% and it passes here
 
Screenshot 2026-03-06 at 12 55 34 PM

but locally, we got 

Screenshot 2026-03-06 at 12 57 18 PM

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

#### Tests

- [x] Added new
- [x] Updated existing
- [ ] Deleted existing

### CODE REVIEW

File: test/io/confluent/intellijplugin/ccloud/auth/CCloudOAuthCallbackServerTest.kt [hunk 1]
```diff
@@ -131,18 +133,21 @@ class CCloudOAuthCallbackServerTest {
             assertTrue(result.html.contains("user@example.com"))
         }
 
-        @Test
```
Comment (Cerchie) [inline test/io/confluent/intellijplugin/ccloud/auth/CCloudOAuthCallbackServerTest.kt:134]: some changes related to refactoring, repeating less code

File: src/io/confluent/intellijplugin/ccloud/auth/CCloudOAuthCallbackServer.kt [hunk 2]
```diff
@@ -126,7 +126,7 @@ class CCloudOAuthCallbackServer(
             is SSLHandshakeException -> 500 to TLS_HANDSHAKE_ERROR_MESSAGE
 
             is OAuthErrorException -> {
-                exception.httpStatusCode to "Retrieving ID token failed: ${exception.errorCode} ${exception.errorCode} - ${exception.errorDescription}."
```
Comment (Cerchie) [inline src/io/confluent/intellijplugin/ccloud/auth/CCloudOAuthCallbackServer.kt:129]: this was double-printed

**Review by bcscc — APPROVED** [review]
LGTM, new tests look good and are passing locally! Thanks for increasing coverage too!
