### PR TITLE
[v253.25910.x] fix: Schema Registry NPE when producing Avro messages with references

### LINKED ISSUE #591: Bug with introspecting Schema Registry and producing Avro message via Kafka plugin
Hey folks!

After latest update made for the plugin (version - 253.25910.0 from Apr 7, 2026, where you apart from other changes - renamed the plugin from "Kafka" to "Confluent") something got broken in the Schema Registry introspection functionality.

For the context:
 - I have Kafka container running locally
 - I have Schema Registry container running locally, with Avro schemas registered in it.
 - I'm trying to produce Avro message defining what schema to use.
 - I'm getting the error (on the below screens).

Image
Image

Rolling back to previous version - 253.25909.4 from Jan 26, 2026 - helped to solve my issue.
But please take a look and apply the fix for the latest version.

Thank you!

### PR DESCRIPTION
**Pull request by bcscc**
## Summary of Changes

- Fix `NullPointerException` in `KafkaRegistryUtil.loadSchema()` when producing Avro messages whose schema has references to other schemas
  - During the `BaseClusterDataManager` refactoring (CCloud support), `loadSchema()` was changed to use unconfigured schema providers that lack a `SchemaVersionFetcher`, causing NPE in `AbstractSchemaProvider.resolveReferences()`. The fix delegates to `dataManager.parseSchemaForDisplay()` which uses properly configured providers from the `ConfluentRegistryClient`.
- Minor: clean up fully-qualified `ParsedSchema` import in `KafkaDataManager`

Fixes #591 

https://github.com/user-attachments/assets/0b426405-7ab4-4a6d-8a33-c5ab548b3072

### Click-testing instructions

1. Run a local Kafka + Schema Registry (e.g., via Docker)
2. Register an Avro schema **with references** (e.g., a `User` schema that references an `Address` schema)
3. Open the plugin, connect to the local cluster, and produce an Avro message using the referencing schema
4. Verify the message is produced successfully without errors
5. Also verify producing with a **simple** Avro schema (no references) still works

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

#### Tests

- [x] Added new
- [ ] Updated existing
- [ ] Deleted existing

### CODE REVIEW

File: src/io/confluent/intellijplugin/registry/KafkaRegistryUtil.kt
Comment (eguicf) [inline src/io/confluent/intellijplugin/registry/KafkaRegistryUtil.kt:82]: consider update this line to top-level import as well

File: src/io/confluent/intellijplugin/data/KafkaDataManager.kt [hunk 1]
```diff
@@ -230,7 +230,7 @@ class KafkaDataManager(
             ?: error(KafkaMessagesBundle.message("error.schema.registry.provider.not.selected"))
     }
 
-    override fun parseSchemaForDisplay(versionInfo: SchemaVersionInfo): Result<io.confluent.kafka.schemaregistry.ParsedSchema> {
+    override fun parseSchemaForDisplay(versionInfo: SchemaVersionInfo): Result<ParsedSchema> {
```
Comment (eguicf) [inline src/io/confluent/intellijplugin/data/KafkaDataManager.kt:233]: nice

**Review by noeldevelops — APPROVED** [review]
Seems like this fixes the issue. Glad it is somewhat simple, and thanks for boosting test coverage while you're here. 🚢

File: test/io/confluent/intellijplugin/registry/KafkaRegistryUtilTest.kt [hunk 2]
```diff
@@ -0,0 +1,213 @@
...
+
+        @JvmStatic
+        @AfterAll
+        fun tearDownAll() {
+            wireMockServer.stop()
+        }
+    }
+
+    private val addressSchemaJson =
+        """{"type":"record","name":"Address","namespace":"com.example","fields":[{"name":"street","type":"string"}]}"""
```
Comment (eguicf) [inline test/io/confluent/intellijplugin/registry/KafkaRegistryUtilTest.kt:52]: Consider moving JSON schema fixtures in this file to separate files in `test/resources/fixtures/`.

**Review by eguicf — APPROVED** [review]
Thanks for the fix, and pairing on this PR! I have a few minor comments but  shouldn't block the merge.

I was able to reproduce the error—it impacted all schema types:

Image

Click-tested the changes and confirmed the error is resolved.

Image
Image
Image


Additional context for the team: @bcscc and I created schemas referencing another schema using the CLI. The plugin (and VS Code extension) currently don't support creating schemas with references through the UI, this might be something worth considering for a future enhancement.
