### PR TITLE
[v253.25910.x] fix: CCloud partition details remain stale after refresh

### LINKED ISSUE #565: Topic details is stale after refresh invoked for CCloud connection
Topic partition details remains stale after refresh invoked in CCloud connection
 
1. Create a empty topic and select it to see the Partitions details panel
2. Start a produce and produce messages into the topic
3. Click "Refresh" button and see that the partitions still don't have any messages in the message count

https://github.com/user-attachments/assets/e3532e17-9c7c-4c1c-9508-71f9ec78cd51

### PR DESCRIPTION
**Pull request by eguicf**
## Summary of Changes

This PR fixes https://github.com/confluentinc/intellij/issues/565.

1. `DataPlaneCache.kt`: Clear topic enrichment cache on `clearTopicCache()`
2. `CCloudClusterDataManager.kt`: Clear partition cache on `cancelAllEnrichmentJobs()`
3. `KafkaMonitoringToolWindowController.kt`: Refresh partition models after cache clear
 
### Click-testing instructions

  1. Create empty CCloud topic
  2. Produce messages
  3. Click Refresh
  4. ✅ Partition details now show updated message counts/offsets, topic geenal panel also show correct total msg counts
  5. ⏺️ **recording**: https://confluent.slack.com/archives/C0ALJ7VEQG0/p1774044253766259?thread_ts=1774042368.244209&cid=C0ALJ7VEQG0

### Optional: Any additional details or context that should be provided?

-

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

#### Tests

- [ ] Added new
- [ ] Updated existing
- [ ] Deleted existing

### CODE REVIEW

File: src/io/confluent/intellijplugin/data/CCloudClusterDataManager.kt [hunk 1]
```diff
@@ -603,6 +603,7 @@ class CCloudClusterDataManager(
             dataPlaneCache.createSchema(versionInfo.schemaName, request)
 
             invalidateSchemaVersionCache(versionInfo.schemaName)
+            updateSingleSchemaInList(versionInfo.schemaName)
```
Comment (eguicf) [inline src/io/confluent/intellijplugin/data/CCloudClusterDataManager.kt:606]: This fixed another small issue that "After schema evolved (e.g to version2) and go back to the schema table panel, newest version number don't display unless manual refresh"

Image

**Review by bcscc — APPROVED** [review]
LGTM, thanks
